# Generated by Django 5.1.7 on 2025-10-31 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AFKEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.CharField(default='Default System', max_length=255)),
                ('event_id', models.IntegerField(default=-1)),
                ('start_time', models.DateTimeField()),
                ('duration', models.FloatField(help_text='Duration in seconds')),
                ('is_afk', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AppUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.CharField(default='Default System', max_length=255)),
                ('event_id', models.IntegerField(default=-1)),
                ('app_name', models.CharField(max_length=255)),
                ('window_title', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('duration', models.FloatField(help_text='Duration in seconds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('productivity_tag', models.CharField(choices=[('productive', 'Productive'), ('unproductive', 'Unproductive'), ('neutral', 'Neutral')], default='neutral', max_length=20)),
            ],
        ),
    ]
