# Generated by Django 5.1.7 on 2025-07-06 07:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_productivity_tracker', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='afkevent',
            name='event_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='afkevent',
            name='system',
            field=models.CharField(default='Default System', max_length=255),
        ),
        migrations.AddField(
            model_name='appusage',
            name='event_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='appusage',
            name='system',
            field=models.CharField(default='Default System', max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='afkevent',
            unique_together={('user', 'system', 'event_id')},
        ),
        migrations.AlterUniqueTogether(
            name='appusage',
            unique_together={('user', 'system', 'event_id')},
        ),
    ]
