# Generated by Django 5.1.7 on 2025-10-31 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_by', models.TextField(choices=[('customer', 'Customer'), ('agent', 'Agent')], default='customer')),
                ('closed_reason', models.TextField(blank=True, null=True)),
                ('status', models.TextField(choices=[('new', 'New'), ('active', 'Active'), ('closed', 'Closed')], default='new')),
                ('subject', models.TextField(blank=True, null=True)),
                ('thread_id', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='IncomingMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.TextField(default='TEXT')),
                ('message_body', models.TextField()),
                ('content_blocks', models.JSONField(blank=True, null=True)),
                ('messageid', models.TextField(blank=True, null=True)),
                ('received_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.TextField(choices=[('unread', 'Unread'), ('read', 'Read'), ('responded', 'Responded')], default='unread')),
                ('status_details', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.TextField(default='text')),
                ('message_body', models.TextField()),
                ('sent_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('status_details', models.TextField(blank=True, null=True)),
                ('messageid', models.TextField(blank=True, null=True)),
                ('template', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
