# Generated by Django 5.1.7 on 2025-03-26 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manage_contact', '0002_initial'),
        ('manage_conversation', '0001_initial'),
        ('manage_organization', '0001_initial'),
        ('manage_platform', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='assigned_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conversation',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conversation',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='manage_contact.contact'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='manage_organization.organization'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='manage_platform.platform'),
        ),
        migrations.AddField(
            model_name='incomingmessage',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_messages', to='manage_contact.contact'),
        ),
        migrations.AddField(
            model_name='incomingmessage',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_messages', to='manage_conversation.conversation'),
        ),
        migrations.AddField(
            model_name='incomingmessage',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_messages', to='manage_organization.organization'),
        ),
        migrations.AddField(
            model_name='incomingmessage',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_messages', to='manage_platform.platform'),
        ),
        migrations.AddField(
            model_name='messageresponselog',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_logs', to='manage_conversation.conversation'),
        ),
        migrations.AddField(
            model_name='messageresponselog',
            name='incoming_message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_logs', to='manage_conversation.incomingmessage'),
        ),
        migrations.AddField(
            model_name='messageresponselog',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_logs', to='manage_organization.organization'),
        ),
        migrations.AddField(
            model_name='messageresponselog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usermessage',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_messages', to='manage_conversation.conversation'),
        ),
        migrations.AddField(
            model_name='usermessage',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_messages', to='manage_organization.organization'),
        ),
        migrations.AddField(
            model_name='usermessage',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_messages', to='manage_platform.platform'),
        ),
        migrations.AddField(
            model_name='usermessage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
