# Generated by Django 5.1.7 on 2025-03-29 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_conversation', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MessageResponseLog',
        ),
    ]
