# Generated by Django 5.1.7 on 2025-05-02 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_conversation', '0003_delete_messageresponselog'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomingmessage',
            name='message_type',
            field=models.TextField(default='TEXT'),
        ),
        migrations.AddField(
            model_name='usermessage',
            name='message_type',
            field=models.TextField(default='TEXT'),
        ),
    ]
