# Generated by Django 5.1.7 on 2025-05-10 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_conversation', '0004_incomingmessage_message_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='open_by',
            field=models.TextField(choices=[('customer', 'Customer'), ('agent', 'Agent')], default='customer'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='status',
            field=models.TextField(choices=[('new', 'New'), ('active', 'Active'), ('closed', 'Closed')], default='new'),
        ),
        migrations.AlterField(
            model_name='incomingmessage',
            name='status',
            field=models.TextField(choices=[('unread', 'Unread'), ('read', 'Read'), ('responded', 'Responded')], default='unread'),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='message_type',
            field=models.TextField(default='text'),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='status',
            field=models.TextField(blank=True, null=True),
        ),
    ]
