# Generated by Django 5.1.7 on 2025-07-10 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_conversation', '0005_alter_conversation_open_by_alter_conversation_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='subject',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incomingmessage',
            name='content_blocks',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
