# Generated by Django 5.1.7 on 2025-07-12 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_conversation', '0006_conversation_subject_incomingmessage_content_blocks'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='thread_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
