# Generated by Django 5.1.7 on 2025-07-12 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_conversation', '0007_conversation_thread_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomingmessage',
            name='message_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
