# Generated by Django 5.1.7 on 2025-07-12 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_conversation', '0008_incomingmessage_message_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incomingmessage',
            old_name='message_id',
            new_name='messageid',
        ),
    ]
