# Generated by Django 5.1.7 on 2025-07-17 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manage_organization', '0004_alter_organization_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('database_name', models.CharField(max_length=128)),
                ('table_name', models.CharField(max_length=128)),
                ('primary_keys', models.JSONField(default=list)),
                ('foreign_keys', models.JSONField(default=list)),
                ('entity_type', models.CharField(blank=True, max_length=64)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='db_mapping', to='manage_organization.organization')),
            ],
            options={
                'unique_together': {('organization', 'database_name', 'table_name')},
            },
        ),
    ]
