# Generated by Django 5.1.7 on 2025-04-12 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_files', '0003_filedownloadevent_filestorageevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='size_gb',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
