# Generated by Django 5.1.7 on 2025-04-18 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_files', '0005_paymentfiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filedownloadevent',
            name='file_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manage_files.file'),
        ),
        migrations.AlterField(
            model_name='filestorageevent',
            name='file_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manage_files.file'),
        ),
    ]
