# Generated by Django 5.1.7 on 2025-04-18 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_files', '0006_alter_filedownloadevent_file_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
