# Generated by Django 5.1.7 on 2025-04-18 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_files', '0007_file_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='s3_key',
            field=models.CharField(max_length=4094),
        ),
    ]
