# Generated by Django 5.1.7 on 2025-05-10 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_files', '0008_alter_file_s3_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='file',
            name='s3_key',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='filedownloadevent',
            name='file_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='filestorageevent',
            name='file_name',
            field=models.TextField(),
        ),
    ]
