# Generated by Django 5.1.7 on 2025-07-04 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_files', '0009_alter_file_name_alter_file_s3_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='signed_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='signed_url_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
