# Generated by Django 5.1.7 on 2025-03-27 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterpriseprofile',
            name='is_privileged',
            field=models.BooleanField(default=False),
        ),
    ]
