# Generated by Django 5.1.7 on 2025-04-19 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_users', '0002_enterpriseprofile_is_privileged'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('employee', 'Employee'), ('owner', 'Owner'), ('agent', 'Agent')], default='individual', max_length=20),
        ),
    ]
