# Generated by Django 5.1.7 on 2025-05-10 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_users', '0003_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.TextField(choices=[('individual', 'Individual'), ('employee', 'Employee'), ('owner', 'Owner'), ('agent', 'Agent')], default='individual'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enterpriseprofile',
            name='uuid',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='owneraccount',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='passwordresetotp',
            name='otp',
            field=models.TextField(),
        ),
    ]
