# Generated by Django 5.1.7 on 2025-05-11 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_users', '0004_alter_customuser_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_payment_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_subscription_complete',
            field=models.BooleanField(default=False),
        ),
    ]
