# Generated by Django 5.1.7 on 2025-07-04 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_users', '0005_customuser_is_payment_complete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_productivity_enable',
            field=models.BooleanField(default=False),
        ),
    ]
