# Generated by Django 5.1.7 on 2025-03-26 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KeyLogger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.TextField()),
                ('app_details', models.TextField()),
                ('idle_time', models.IntegerField()),
            ],
        ),
    ]
