# Generated by Django 5.1.7 on 2025-10-31 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auto_allocation_enabled', models.BooleanField(default=False)),
                ('auto_allocation_algorithm', models.TextField(choices=[('rr', 'RoundRobin'), ('bw', 'BandWidth')], default='rr')),
            ],
        ),
    ]
