# Generated by Django 5.1.7 on 2025-04-20 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_organization', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='robo_name',
        ),
    ]
