# Generated by Django 5.1.7 on 2025-05-10 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_organization', '0003_remove_organization_robo_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.TextField(unique=True),
        ),
    ]
