# Generated by Django 5.1.7 on 2025-05-10 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_subscriptions', '0003_payment_is_wallet_topup_alter_payment_subscription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apps',
            name='app_name',
            field=models.TextField(help_text='The app this subscription belongs to', unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.TextField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='status',
            field=models.TextField(choices=[('pending', 'Pending'), ('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending'),
        ),
    ]
