# Generated by Django 5.1.7 on 2025-05-12 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_subscriptions', '0004_alter_apps_app_name_alter_payment_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='is_wallet_topup',
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_type',
            field=models.CharField(choices=[('subscription', 'Subscription'), ('wallet_topup', 'Wallet Top-Up'), ('app_usage', 'App Usage')], default='subscription', max_length=20),
        ),
    ]
