# Generated by Django 5.1.7 on 2025-05-24 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manage_organization', '0004_alter_organization_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='GmailAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(max_length=254, unique=True)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('token_expiry', models.DateTimeField()),
                ('history_id', models.CharField(blank=True, max_length=255, null=True)),
                ('last_watch_time', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_organization.organization')),
            ],
        ),
        migrations.CreateModel(
            name='GmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=128, unique=True)),
                ('thread_id', models.CharField(max_length=128)),
                ('subject', models.CharField(blank=True, max_length=512, null=True)),
                ('sender', models.EmailField(blank=True, max_length=254, null=True)),
                ('snippet', models.TextField(blank=True, null=True)),
                ('internal_date', models.DateTimeField()),
                ('labels', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gmail_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_email.gmailaccount')),
            ],
        ),
    ]
