# Generated by Django 5.1.7 on 2025-10-31 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GmailAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(max_length=254, unique=True)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('token_expiry', models.DateTimeField()),
                ('history_id', models.CharField(blank=True, max_length=255, null=True)),
                ('last_watch_time', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='GmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=128, unique=True)),
                ('thread_id', models.CharField(max_length=128)),
                ('subject', models.CharField(blank=True, max_length=512, null=True)),
                ('sender', models.EmailField(blank=True, max_length=254, null=True)),
                ('to', models.TextField(blank=True, null=True)),
                ('cc', models.TextField(blank=True, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('email_date', models.DateTimeField()),
                ('labels', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
