# Generated by Django 5.1.7 on 2025-07-04 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_email', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gmailmessage',
            old_name='snippet',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='gmailmessage',
            old_name='internal_date',
            new_name='email_date',
        ),
        migrations.AddField(
            model_name='gmailmessage',
            name='cc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gmailmessage',
            name='to',
            field=models.TextField(blank=True, null=True),
        ),
    ]
