# Generated by Django 5.1.7 on 2025-10-31 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manage_contact', '0001_initial'),
        ('manage_organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contact',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='manage_organization.organization'),
        ),
        migrations.AddField(
            model_name='contactcustomfield',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_custom_fields', to='manage_organization.organization'),
        ),
        migrations.AddField(
            model_name='contactcustomfieldvalue',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_field_values', to='manage_contact.contact'),
        ),
        migrations.AddField(
            model_name='contactcustomfieldvalue',
            name='custom_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_contact.contactcustomfield'),
        ),
        migrations.AddField(
            model_name='contactgroup',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contactgroup',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_groups', to='manage_organization.organization'),
        ),
        migrations.AddField(
            model_name='groupmember',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='manage_contact.contact'),
        ),
        migrations.AddField(
            model_name='groupmember',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='manage_contact.contactgroup'),
        ),
        migrations.AddField(
            model_name='groupmember',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_member', to='manage_organization.organization'),
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.UniqueConstraint(fields=('phone', 'organization'), name='unique_phone_per_org'),
        ),
        migrations.AlterUniqueTogether(
            name='contactcustomfield',
            unique_together={('organization', 'key')},
        ),
        migrations.AlterUniqueTogether(
            name='contactcustomfieldvalue',
            unique_together={('contact', 'custom_field')},
        ),
        migrations.AddConstraint(
            model_name='contactgroup',
            constraint=models.UniqueConstraint(fields=('name', 'organization'), name='unique_group_name_per_org'),
        ),
        migrations.AlterUniqueTogether(
            name='groupmember',
            unique_together={('group', 'contact')},
        ),
    ]
