# Generated by Django 5.1.7 on 2025-03-27 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_contact', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmember',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='groupmember',
            name='organization',
        ),
    ]
