# Generated by Django 5.1.7 on 2025-03-27 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_contact', '0003_remove_groupmember_created_at_and_more'),
        ('manage_organization', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmember',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contact_member', to='manage_organization.organization'),
            preserve_default=False,
        ),
    ]
