# Generated by Django 5.1.7 on 2025-05-10 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_contact', '0004_groupmember_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='category',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='contactgroup',
            name='category',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contactgroup',
            name='name',
            field=models.TextField(unique=True),
        ),
    ]
