# Generated by Django 5.1.7 on 2025-05-17 07:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_contact', '0005_alter_contact_category_alter_contact_name_and_more'),
        ('manage_organization', '0004_alter_organization_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.UniqueConstraint(fields=('phone', 'organization'), name='unique_phone_per_org'),
        ),
        migrations.AddConstraint(
            model_name='contactgroup',
            constraint=models.UniqueConstraint(fields=('name', 'organization'), name='unique_group_name_per_org'),
        ),
    ]
