# Generated by Django 5.1.7 on 2025-05-17 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_contact', '0006_contact_unique_phone_per_org_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='contactgroup',
            name='name',
            field=models.TextField(),
        ),
    ]
