# Generated by Django 5.1.7 on 2025-05-18 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_contact', '0007_alter_contact_phone_alter_contactgroup_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='platform_name',
            field=models.TextField(choices=[('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('gmail', 'Gmail'), ('webchat', 'Webchat')], default='whatsapp'),
        ),
    ]
