# Generated by Django 5.1.7 on 2025-07-06 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_contact', '0002_add_missing_tables'),
        ('manage_contact', '0008_contact_platform_name'),
    ]

    operations = [
    ]
