# Generated by Django 5.1.7 on 2025-07-06 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_contact', '0009_merge_20250706_0709'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='image_expires_at',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='platform_name',
            field=models.TextField(choices=[('whatsapp', 'WhatsApp'), ('messenger', 'Messenger'), ('telegram', 'Telegram'), ('gmail', 'Gmail'), ('webchat', 'Webchat')], default='whatsapp'),
        ),
    ]
