# Generated by Django 5.1.7 on 2025-03-26 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('recipient_type', models.CharField(choices=[('individual', 'Individual'), ('group', 'Group')], max_length=20)),
                ('recipient_id', models.IntegerField()),
                ('frequency', models.IntegerField(default=-1)),
                ('message_body', models.TextField()),
                ('scheduled_time', models.DateTimeField()),
                ('datasource', models.JSONField(blank=True, null=True)),
                ('excel_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('canceled', 'Canceled'), ('failed', 'Failed')], default='scheduled', max_length=20)),
                ('msg_status', models.CharField(blank=True, choices=[('', 'Pending'), ('sent_to_server', 'Sent to Server'), ('delivered', 'Delivered'), ('read', 'Read'), ('sent', 'Sent'), ('failed', 'Failed')], default='', max_length=20)),
                ('sent_time', models.DateTimeField(blank=True, null=True)),
                ('messageid', models.TextField(blank=True, null=True)),
                ('template', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
