# Generated by Django 5.1.7 on 2025-10-31 13:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_message', models.TextField(blank=True, null=True)),
                ('messageid', models.TextField(blank=True, default=None, null=True)),
                ('status', models.TextField(default='success')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('recipient_type', models.TextField(choices=[('individual', 'Individual'), ('group', 'Group')])),
                ('recipient_id', models.IntegerField()),
                ('frequency', models.IntegerField(default=-1)),
                ('message_body', models.TextField()),
                ('scheduled_time', models.DateTimeField()),
                ('datasource', models.JSONField(blank=True, null=True)),
                ('excel_filename', models.TextField(blank=True, null=True)),
                ('status', models.TextField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('warning', 'Warning'), ('scheduled_warning', 'Scheduled Warning'), ('completed', 'Completed'), ('failed', 'Failed')], default='scheduled')),
                ('msg_status', models.TextField(blank=True, choices=[('', 'Pending'), ('sent_to_server', 'Sent to Server'), ('delivered', 'Delivered'), ('read', 'Read'), ('sent', 'Sent'), ('failed', 'Failed')], default='')),
                ('sent_time', models.DateTimeField(blank=True, null=True)),
                ('messageid', models.TextField(blank=True, null=True)),
                ('template', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
