# Generated by Django 5.1.7 on 2025-10-31 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manage_campaign', '0001_initial'),
        ('manage_contact', '0001_initial'),
        ('manage_organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformlog',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_organization.organization'),
        ),
        migrations.AddField(
            model_name='platformlog',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_contact.contact'),
        ),
        migrations.AddField(
            model_name='scheduledmessage',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_messages', to='manage_organization.organization'),
        ),
    ]
