# Generated by Django 5.1.7 on 2025-10-31 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manage_campaign', '0002_initial'),
        ('manage_platform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledmessage',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_messages', to='manage_platform.platform'),
        ),
    ]
