# Generated by Django 5.1.7 on 2025-03-29 01:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_campaign', '0004_initial'),
        ('manage_contact', '0004_groupmember_organization'),
        ('manage_organization', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_message', models.CharField(blank=True, max_length=200, null=True)),
                ('messageid', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('status', models.CharField(default='success', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_organization.organization')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_contact.contact')),
                ('scheduled_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_campaign.scheduledmessage')),
            ],
        ),
    ]
