# Generated by Django 5.1.7 on 2025-04-09 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_campaign', '0005_platformlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledmessage',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='scheduled', max_length=20),
        ),
    ]
