# Generated by Django 5.1.7 on 2025-05-10 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_campaign', '0006_alter_scheduledmessage_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformlog',
            name='log_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='platformlog',
            name='messageid',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='platformlog',
            name='status',
            field=models.TextField(default='success'),
        ),
        migrations.AlterField(
            model_name='scheduledmessage',
            name='excel_filename',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scheduledmessage',
            name='msg_status',
            field=models.TextField(blank=True, choices=[('', 'Pending'), ('sent_to_server', 'Sent to Server'), ('delivered', 'Delivered'), ('read', 'Read'), ('sent', 'Sent'), ('failed', 'Failed')], default=''),
        ),
        migrations.AlterField(
            model_name='scheduledmessage',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='scheduledmessage',
            name='recipient_type',
            field=models.TextField(choices=[('individual', 'Individual'), ('group', 'Group')]),
        ),
        migrations.AlterField(
            model_name='scheduledmessage',
            name='status',
            field=models.TextField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='scheduled'),
        ),
    ]
