# Generated by Django 5.1.7 on 2025-05-10 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_campaign', '0007_alter_platformlog_log_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledmessage',
            name='status',
            field=models.TextField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('warning', 'Warning'), ('scheduled_warning', 'Scheduled Warning'), ('completed', 'Completed'), ('failed', 'Failed')], default='scheduled'),
        ),
    ]
