# Generated by Django 5.1.7 on 2025-10-31 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manage_organization', '0002_initial'),
        ('manage_platform', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='blockedcontact',
            name='blocked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='platform',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platforms', to='manage_organization.organization'),
        ),
        migrations.AddField(
            model_name='platform',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platforms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gmailaccount',
            name='platform',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gmail_account', to='manage_platform.platform'),
        ),
        migrations.AddField(
            model_name='blockedcontact',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_contacts', to='manage_platform.platform'),
        ),
        migrations.AddField(
            model_name='processedgmailmessage',
            name='gmail_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processed_messages', to='manage_platform.gmailaccount'),
        ),
        migrations.AddConstraint(
            model_name='platform',
            constraint=models.UniqueConstraint(fields=('organization', 'user_platform_name'), name='unique_user_platform_per_org'),
        ),
        migrations.AddIndex(
            model_name='blockedcontact',
            index=models.Index(fields=['platform', 'contact_value'], name='manage_plat_platfor_31e3c1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='blockedcontact',
            unique_together={('platform', 'contact_value')},
        ),
    ]
