# Generated by Django 5.1.7 on 2025-03-27 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_organization', '0002_initial'),
        ('manage_platform', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='organization',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='platforms', to='manage_organization.organization'),
            preserve_default=False,
        ),
    ]
