# Generated by Django 5.1.7 on 2025-04-09 09:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_organization', '0002_initial'),
        ('manage_platform', '0003_platform_organization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='user_platform_name',
            field=models.CharField(default='whatsapp', max_length=50),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='platform',
            constraint=models.UniqueConstraint(fields=('organization', 'user_platform_name'), name='unique_user_platform_per_org'),
        ),
    ]
