# Generated by Django 5.1.7 on 2025-05-10 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_platform', '0004_platform_user_platform_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='app_id',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='platform',
            name='login_id',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='platform',
            name='platform_name',
            field=models.TextField(choices=[('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('gmail', 'Gmail')]),
        ),
        migrations.AlterField(
            model_name='platform',
            name='status',
            field=models.TextField(default='active'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='user_platform_name',
            field=models.TextField(),
        ),
    ]
