# Generated by Django 5.1.7 on 2025-05-17 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_platform', '0005_alter_platform_app_id_alter_platform_login_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='secret_key',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
