# Generated by Django 5.1.7 on 2025-05-18 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_platform', '0006_platform_secret_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='platform_name',
            field=models.TextField(choices=[('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('gmail', 'Gmail'), ('webchat', 'Webchat')]),
        ),
    ]
