# Generated by Django 5.1.7 on 2025-07-04 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_platform', '0007_alter_platform_platform_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='platform_name',
            field=models.TextField(choices=[('whatsapp', 'WhatsApp'), ('messenger', 'Messenger'), ('telegram', 'Telegram'), ('gmail', 'Gmail'), ('webchat', 'Webchat')]),
        ),
    ]
