# Generated by Django 5.1.7 on 2025-07-06 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_platform', '0008_alter_platform_platform_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='GmailAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(max_length=254, unique=True)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('token_expiry', models.DateTimeField()),
                ('watch_expiry', models.DateTimeField(blank=True, null=True)),
                ('history_id', models.CharField(blank=True, max_length=255, null=True)),
                ('last_watch_time', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gmail_account', to='manage_platform.platform')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessedGmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=255, unique=True)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('gmail_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processed_messages', to='manage_platform.gmailaccount')),
            ],
        ),
    ]
