# Generated by Django 5.1.7 on 2025-07-10 09:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_platform', '0009_gmailaccount_processedgmailmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_value', models.TextField(help_text='Phone number or email address to block')),
                ('contact_type', models.CharField(choices=[('phone', 'Phone'), ('email', 'Email')], max_length=20)),
                ('reason', models.TextField(blank=True, null=True)),
                ('blocked_at', models.DateTimeField(auto_now_add=True)),
                ('blocked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_contacts', to='manage_platform.platform')),
            ],
            options={
                'indexes': [models.Index(fields=['platform', 'contact_value'], name='manage_plat_platfor_31e3c1_idx')],
                'unique_together': {('platform', 'contact_value')},
            },
        ),
    ]
