# Generated by Django 5.1.7 on 2025-07-12 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_platform', '0010_blockedcontact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockedcontact',
            name='contact_type',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('messenger', 'Messenger'), ('telegram', 'Telegram'), ('gmail', 'Gmail'), ('webchat', 'Webchat')], max_length=20),
        ),
    ]
